name: scoping_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  # R Base e Ferramentas de Sistema
  - r-base=4.5.2
  - make       
  - compilers  
  - gsl         
  - mpfr        

  # Pacotes R Essenciais (Data Science)
  - r-tidyverse
  - r-readxl   
  - r-writexl   
  - r-devtools  
  - r-rmarkdown 
  - r-shiny     
  
  # Havia me esquecido :)
  - r-bibliometrix

  # Bibliotecas de Texto 
  - r-tm        
  - r-snowballc 
  - r-lda
